[features]
seeds = false
skip-lint = false
[programs.localnet]
solquad = "GqzFCsCANL7mGeidazdsRWCzyqnXuvqJoFAcrFWVed2o"

[programs.devnet]
solquad = "GqzFCsCANL7mGeidazdsRWCzyqnXuvqJoFAcrFWVed2o"

[registry]
url = "https://api.apr.dev"

[provider.localnet]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[provider.devnet]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
